[package]
name = "qemu-tests"
version = "0.0.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
description = "Test salty using QEMU musca-b1"
license = "Apache-2.0 OR MIT"

[dependencies]
cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.5"
hex-literal = "0.2.1"
panic-semihosting = { version = "0.5.3", features = ["exit"] }
# subtle = { version = "2.2", default-features = false }
wycheproof = { version = "0.1", path = "../wycheproof" }
wycheproof-gen = { version = "0.1", path = "../wycheproof/wycheproof-gen" }

[dependencies.salty]
path = ".."

[features]
slow = ["salty/slow-motion"]

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"

[[bin]]
name = "qemu-tests"
path = "src/main.rs"

[[bin]]
name = "wycheproof"
path = "src/bin/wycheproof_on_target/main.rs"
